- name: metal_get_ncb_userdata_file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/dlotterman/metal_code_snippets/main/virtual_appliance_host/no_code_with_guardrails/cloud_inits/el9_no_code_safety_first_appliance_host.mime
    dest: /tmp/tmp_plath_el9_no_code_safety_first_appliance_host.mime
    mode: '0640'

- name: metal_get_or_provision_ncb
  equinix.cloud.metal_device:
    project_id: YOURID
    metal_api_token: YOURTOKEN
    hostname: "ncb-{{ plath_domain }}-01"
    tags: plath,plath_el9,plath_ncb,plath_ansible,plath_mgmt_networking
    operating_system: alma_9
    metro: "{{ metal_metro }}"
    userdata: "{{ lookup('file', '/tmp/tmp_plath_el9_no_code_safety_first_appliance_host.mime') }}"
    plan: "{{ metal_ncb_config }}"
    state: present
  register: metal_get_or_provision_ncb_output
