#cloud-config
#
#This cloud-init primarily does three things.
#1) Via firewalld, shuts all ports, then opens up
#    * 22 (SSH) in from the world
#    * All traffic in from the Metal management network (10.0.0.0/8)
#    * Traffic to cockpit
#2) Setups fail2ban to block abusive SSH login attempts and cockpit login attempts 
#3) Enables dnf automatic, which will automatically update packages \
#This is all in the persuit of having operator "safety" guards
#for instances that will be managed collaboratively

package_upgrade: true
package_reboot_if_required: true

yum_repos:
    epel-release:
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
        enabled: true
        gpgcheck: true
        gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        name: Extra Packages for Enterprise Linux $releasever - $basearch

packages:
 - dnf-plugins-core
 - fail2ban
 - iperf3
 - screen
 - ethtool
 - strace
 - unzip
 - jq
 - dnf-automatic
 - virt-manager
 - bridge-utils
 - libguestfs
 - cockpit
 - cockpit-machines
 - cockpit-storaged
 - cockpit-podman
 - cockpit-system
 - cockpit-bridge
 - cockpit-pcp

groups:
 - cloud-users

users:
  - name: adminuser
    primary_group: cloud-users
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: [cloud-users, sudo]
    shell: /bin/bash

datasource:
  Ec2:
    strict_id: false

# keep sshd disabled till everything is done at the end of runcmd
bootcmd:
  - [ cloud-init-per, instance, systemctl, stop, sshd ]
  - [ cloud-init-per, instance, systemctl, disable, sshd ]
  - systemctl stop kdump || true
  - systemctl disable kdump || true
 
runcmd:
  - systemctl stop sshd || true
  - systemctl disable sshd || true
  - systemctl stop iscsi
  - systemctl stop nis-domainname  
  - systemctl stop iscsi-onboot
  - systemctl stop nfs-convert
  - systemctl disable iscsi
  - systemctl disable nis-domainname
  - systemctl disable iscsi-onboot
  - systemctl disable nfs-convert
  - dnf upgrade -y
  - systemctl reset-failed
  - dnf config-manager --set-enabled powertools
  - echo "8021q"  >> /etc/modules-load.d/networking.conf
  - modprobe 8021q
  - echo "ZONE=trusted" >> /etc/sysconfig/network-scripts/ifcfg-bond0:0
  - sed -i -e '/^AllowZoneDrifting/s/^.*$/AllowZoneDrifting=no/' /etc/firewalld/firewalld.conf
  - systemctl enable fail2ban
  - systemctl enable firewalld
  - systemctl start fail2ban
  - systemctl start firewalld
  - systemctl restart systemd-modules-load.service
  - firewall-cmd --permanent --zone=public --set-target=DROP
  - firewall-cmd --permanent --zone=public --add-service=ssh
  - firewall-cmd --permanent --zone=public --add-service=cockpit
  - firewall-cmd --permanent --zone=trusted --add-source=10.0.0.0/8
  - firewall-cmd --permanent --zone=trusted --add-source=172.16.0.0/12
  - firewall-cmd --reload
  - rsync -av /root/.ssh /home/adminuser/
  - chown -R adminuser:cloud-users /home/adminuser/.ssh
  - sed -i -e '/^#PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - sed -i -e '/^PermitRootLogin/s/^.*$/PermitRootLogin no/' /etc/ssh/sshd_config
  - systemctl restart network
  - systemctl enable NetworkManager  
  - systemctl start NetworkManager
  - systemctl enable libvirtd
  - systemctl start libvirtd
  - systemctl enable pmlogger
  - systemctl start pmlogger
  - systemctl enable pmcd
  - systemctl start pmcd
  - systemctl enable --now cockpit.socket
  - systemctl start cockpit  
  - systemctl enable --now dnf-automatic-install.timer
  - systemctl enable sshd  
  - systemctl start sshd
  - systemctl enable podman
  - systemctl start podman
  - mkdir -p /data/isos/
  - [ wget, --quiet, "https://s3.wasabisys.com/packetrepo/pfSense-CE-2.5.0-RELEASE-amd64.iso", -O, /data/isos/pfsense.iso ]

write_files:
  - owner: root:root
    path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      banaction = iptables-multiport
      ignoreip = 127.0.0.1/8 10.0.0.0/8
      findtime = 600
      maxretry = 5
      [sshd]
      enabled = true
      logpath = %(sshd_log)s
      [pam-generic]
      enabled = true
      logpath = /var/log/secure
    permissions: '0644'
  - owner: root:root
    path: /etc/dnf/automatic.conf
    content: |
      [commands]
      upgrade_type = default
      apply_updates = yes
      download_updates = yes
      [emitters]
      emit_via = motd
    permissions: '0644'
  - owner: root:root
    path: /etc/crontab
    append: true
    content: |
      05 11 * * * root systemctl restart sshd
      10 11 * * * root systemctl restart cockpit.service
      15 11 * * * root systemctl restart serial-getty@ttyS1.service
      20 11 * * * root systemctl restart getty@tty1.service
    permissions: '0644'
  - owner: root:root
    path: /etc/pam.d/password-auth
    content: |
      #%PAM-1.0
      # This file is auto-generated.
      # User changes will be destroyed the next time authselect is run.
      # # User changes will be destroyed the next time authselect is run.
      auth        required      pam_env.so
      auth        required      pam_faillock.so preauth audit deny=5 unlock_time=600 even_deny_root
      auth        sufficient    pam_unix.so try_first_pass nullok
      auth        [default=die] pam_faillock.so authfail audit deny=5 unlock_time=600 even_deny_root
      auth        required      pam_deny.so
      account     required      pam_unix.so
      account     required      pam_faillock.so
      password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
      password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow
      password    required      pam_deny.so
      session     optional      pam_keyinit.so revoke
      session     required      pam_limits.so
      -session     optional      pam_systemd.so
      session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
      session     required      pam_unix.so
    permissions: '0644'
  - owner: root:root
    path: /etc/pam.d/system-auth
    content: |
      #%PAM-1.0
      # This file is auto-generated.
      # User changes will be destroyed the next time authselect is run.
      # # User changes will be destroyed the next time authselect is run.
      auth        required      pam_env.so
      auth        required      pam_faillock.so preauth audit deny=5 unlock_time=600 even_deny_root
      auth        sufficient    pam_unix.so try_first_pass nullok
      auth        [default=die] pam_faillock.so authfail audit deny=5 unlock_time=600 even_deny_root
      auth        required      pam_deny.so
      account     required      pam_unix.so
      account     required      pam_faillock.so
      password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
      password    sufficient    pam_unix.so try_first_pass use_authtok nullok sha512 shadow
      password    required      pam_deny.so
      session     optional      pam_keyinit.so revoke
      session     required      pam_limits.so
      -session     optional      pam_systemd.so
      session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
      session     required      pam_unix.so
    permissions: '0644'
