# This file should be considered broken, deprecated and unmaintained
#
# See alma_linux


#cloud-config

package_upgrade: true
package_reboot_if_required: true

yum_repos:
    epel-release:
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/Everything/$basearch
        enabled: true
        failovermethod: priority
        gpgcheck: true
        gpgkey: http://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
        name: Extra Packages for Enterprise Linux $releasever - $basearch

packages:
 - fail2ban
 - iperf3
 - screen
 - ethtool
 
runcmd:
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - systemctl start firewalld
  - systemctl enable firewalld
  - firewall-cmd --permanent --zone=public --add-service=ssh
  - firewall-cmd --permanent --zone=public --add-source=10.0.0.0/8
  - firewall-cmd --reload

write_files:
  - owner: root:root
    path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      banaction = iptables-multiport
      ignoreip = 127.0.0.1/8 10.0.0.0/8
      findtime = 600
      maxretry = 5
      [sshd]
      enabled = true
      logpath = %(sshd_log)s
    permissions: '0644'
