#cloud-config

## THIS ONE IS NOT COPY PASTEABLE, SEARCH "MODIFY HERE" or about at line 21ish

# Package updates are handled below
package_upgrade: false
package_reboot_if_required: false


packages:
  - fail2ban

runcmd:
  - [systemctl, enable, --now, fail2ban]
  - [systemctl, enable, --now, unattended-upgrades]
  - [systemctl, enable, --now, ufw]
  - [ufw, default, allow, outgoing]
  - [ufw, default, deny, incoming]
  - [ufw, allow, from, 10.0.0.1/8, to, any, port, 22]
  #### MODIFY HERE
  - [ufw, allow, from, YOUR_VPN_CONCENTRATOR_IP, to, any, port, 22]
  - [ufw, enable]
  - [modprobe, 8021q]
  - [sed, -i, -e, '/^#MaxAuthTries/s/^.*$/MaxAuthTries 5/', /etc/ssh/sshd_config]
  - [sed, -i, -e, '/^X11Forwarding/s/^.*$/X11Forwarding no/', /etc/ssh/sshd_config]
  - [bash, /usr/lib/apt/apt.systemd.daily]

write_files:
  - owner: root:root
    path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      banaction = ufw
      ignoreip = 127.0.0.1/8 10.0.0.0/8 172.91.2.151/32
      findtime = 600
      maxretry = 5
      [sshd]
      enabled = true
      logpath = %(sshd_log)s
      mode = aggressive
    permissions: '0644'

  - owner: root:root
    path: /etc/apt/apt.conf.d/50unattended-upgrades
    content: |
      Unattended-Upgrade::Allowed-Origins {
      "${distro_id}:${distro_codename}";
      "${distro_id}:${distro_codename}-updates";
      "${distro_id}:${distro_codename}-security";
      "${distro_id}ESMApps:${distro_codename}-apps-security";
      "${distro_id}ESM:${distro_codename}-infra-security";
      };
    permissions: '0644'

  - owner: root:root
    path: /etc/apt/apt.conf.d/21auto-upgrades_on
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Download-Upgradeable-Packages "1";
      APT::Periodic::AutocleanInterval "7";
      APT::Periodic::Unattended-Upgrade "1";
    permissions: '0644'
  - owner: root:root
    path: /etc/crontab
    append: true
    content: |
      05 * * * * root /usr/bin/unattended-upgrade -v
      05 11 * * * root systemctl restart sshd
      15 11 * * * root systemctl restart serial-getty@ttyS1.service
      20 11 * * * root systemctl restart getty@tty1.service
    permissions: '0644'

  - path: "/etc/modules-load.d/8021q.conf"
    permissions: "0644"
    owner: "root:root"
    append: true
    content: |
      8021q
