#cloud-config

package_upgrade: true
package_reboot_if_required: true

packages:
 - screen
 - sysbench
 - ethtool
 - fail2ban
 - iperf3
 - lshw
 - pciutils
 - ufw
 - vlan
 - arping

runcmd:
  - systemctl enable fail2ban
  - systemctl start fail2ban
  - ufw default allow outgoing
  - ufw default deny incoming
  - ufw allow ssh
  - ufw allow from 10.0.0.1/8
  - ufw enable
  - systemctl enable ufw
  - systemctl start ufw
  - echo "8021q" >> /etc/modules

write_files:
  - owner: root:root
    path: /etc/fail2ban/jail.local
    content: |
      [DEFAULT]
      bantime = 3600
      banaction = ufw
      ignoreip = 127.0.0.1/8 10.0.0.0/8
      findtime = 600
      maxretry = 5
      [sshd]
      enabled = true
      logpath = %(sshd_log)s
      mode = aggressive
    permissions: '0644'
