---
- hosts: tag_osc
  vars:
    glance_mysql_password: glancemysql1234
    glance_admin_password: glanceadmin1234

  tasks:
    - name: openstack_install_glance_packages
      become: yes
      become_method: sudo
      ansible.builtin.package:
        name:
          - glance
        state: latest

    - name: openstack_glance_mysql_db_create
      become: yes
      become_method: sudo
      mysql_db:
        name: glance
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: openstack_glance_mysql_user_create
      become: yes
      become_method: sudo
      mysql_user:
        name: glance
        password: "{{ glance_mysql_password }}"
        priv: 'glance.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
        host: "{{ item }}"
      with_items:
        - 127.0.0.1
        - ::1
        - localhost
        - '%'

    # Need to var and or rework all of this
    - name: openstack_glance_osuser_create
      become: yes
      become_method: sudo
      command: |
        openstack user create --domain default --password glanceadmin1234 glance \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosusercreate.lock
      register: glanceosusercreate

    - name: openstack_glance_osuser_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosusercreate.lock
        state: touch
      when: glanceosusercreate.changed

    - name: openstack_glance_osrole_create
      become: yes
      become_method: sudo
      command: |
        openstack role add --project service --user glance admin \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosrolecreate.lock
      register: glanceosrolecreate

    - name: openstack_glance_osrole_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosrolecreate.lock
        state: touch
      when: glanceosrolecreate.changed

    - name: openstack_glance_osservice_create
      become: yes
      become_method: sudo
      command: |
        openstack service create --name glance --description "os_image" image \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosservicecreate.lock
      register: glanceosservicecreate

    - name: openstack_glance_osservice_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosservicecreate.lock
        state: touch
      when: glanceosservicecreate.changed

    - name: openstack_glance_osendpoint_public_create
      become: yes
      become_method: sudo
      command: |
        openstack endpoint create --region RegionOne image public http://controller:9292 \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosendpointpublic.lock
      register: glanceosendpointpublic

    - name: openstack_glance_osendpoint_public_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosendpointpublic.lock
        state: touch
      when: glanceosendpointpublic.changed

    - name: openstack_glance_osendpoint_internal_create
      become: yes
      become_method: sudo
      command: |
        openstack endpoint create --region RegionOne image internal http://controller:9292 \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosendpointinternal.lock
      register: glanceosendpointinternal

    - name: openstack_glance_osendpoint_internal_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosendpointinternal.lock
        state: touch
      when: glanceosendpointinternal.changed

    - name: openstack_glance_osendpoint_admin_create
      become: yes
      become_method: sudo
      command: |
        openstack endpoint create --region RegionOne image admin http://controller:9292 \
        --os-username admin \
        --os-project-name admin \
        --os-user-domain-id default \
        --os-project-domain-id default \
        --os-identity-api-version 3 \
        --os-auth-url http://controller:5000 \
        --os-password keystoneadmin1234 \
      args:
        strip_empty_ends: false
        creates: /metal/lock/glanceosendpointadmin.lock
      register: glanceosendpointadmin

    - name: openstack_glance_osendpoint_admin_create_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glanceosendpointadmin.lock
        state: touch
      when: glanceosendpointadmin.changed

    - name: openstack_glance_template_conf
      become: yes
      become_method: sudo
      template:
        src: glance-api.conf.j2
        dest: /etc/glance/glance-api.conf
      register: glance_conf

    - name: openstack_glance_restart
      become: yes
      become_method: sudo
      ansible.builtin.service:
        name: glance-api
        state: restarted
        enabled: yes
      when: glance_conf.changed

      #This is so horrible. Why?
    - name: openstack_glance_db_populate
      become: yes
      become_method: sudo
      shell:  su -s /bin/sh -c "glance-manage db_sync" glance
      args:
        creates: /metal/lock/glancemanagedbsync.lock
      register: glancemanagedbsync

    - name: openstack_glance_db_touch_file
      become: yes
      become_method: sudo
      file:
        path: /metal/lock/glancemanagedbsync.lock
        state: touch
      when: glancemanagedbsync.changed

    - name: openstack_service_restart_apache
      become: yes
      become_method: sudo
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes
      when: glancemanagedbsync.changed or glance_conf.changed
