---
- name: install_ufw
  apt: name=ufw
- name: ufw_logging
  ufw:
    logging: 'off'
- name: ufw_allow_ssh
  ufw: proto=tcp port=22 rule=allow
- name: ufw_allow_iperf
  ufw: proto=tcp port=5001 rule=allow src={{ workstation_ip }}
- name: ufw_allow_all_access_from_RFC1918
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
- name: Set ufw policy
  ufw: state=enabled direction=incoming policy=deny
