---
- name: os_packages_install
  apt:
    update_cache: true
    pkg:
      - fail2ban
      - ntpdate
      - strace
      - xfsprogs
      - smartmontools
      - moreutils
      - iperf
      - iperf3
    state: latest
