---
- name: os_settings_security_limits_wildcard
      # http://manpages.ubuntu.com/manpages/bionic/man5/limits.conf.5.html
      # NOTE: group and wildcard limits are not applied to the root user. To set a limit for
      # the root user, this field must contain the literal username root.
  pam_limits:
    domain: '*'
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 65536 }
    - { limit_type: '-', limit_item: 'nproc', value: 65536 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }

  
- name: os_settings_security_limits_root
  pam_limits:
    domain: 'root'
    limit_type: "{{item.limit_type}}"
    limit_item: "{{item.limit_item}}"
    value: "{{item.value}}"
  with_items:
    - { limit_type: '-', limit_item: 'nofile', value: 65536 }
    - { limit_type: '-', limit_item: 'nproc', value: 65536 }
    - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
    - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
  ##register: security_limits_root

- name: os_settings_sysctl_settings_set
  sysctl:
    name: fs.file-max
    value: '150000'
    sysctl_set: yes


- name: os_settings_systemd_iscsid_stop
  systemd:
    name: iscsid
    state: stopped
- name: os_settings_systemd_exim_stop
  systemd:
    name: exim4
    state: stopped
